In [3]:
%load_ext autoreload
%autoreload 2
import numpy as np
random_seed = np.random.randint(100)
random_seed = 0

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
from pnot.utils import Lmatrix2paths, nested
n_sample = 10000
T = 3
L = np.array([[1, 0, 0], [2, 4, 0], [3, 2, 1]])
X, A = Lmatrix2paths(L, n_sample, seed=random_seed, verbose=False)
M = np.array([[1, 0, 0], [2, 3, 0], [3, 1, 2]])
Y, B = Lmatrix2paths(M, n_sample, seed=random_seed, verbose=False)
print(L)
print(M)

nested(X,Y)

[[1 0 0]
 [2 4 0]
 [3 2 1]]
[[1 0 0]
 [2 3 0]
 [3 1 2]]
Start computing
Timestep 2
Computing 20374000 OTs .......
Timestep 1
Computing 4761 OTs .......
Timestep 0
Computing 1 OTs .......
5.41135 seconds
AW_2^2: 3.39547
Finish


3.395468352669553